// ============================================================
//  Mini Dictaphone V1
//  by ponpon 76
//  Open source - libre de réutilisation et modification
//  Fichier : langues.js (traductions 6 langues)
//  6 langues : FR, EN, ES, PT, DE, IT
//  Fichier modifiable : si une traduction vous semble
//  perfectible, corrigez-la ici.
// ============================================================

const TEXTES = {
  // ===== FRANÇAIS =====
  fr: {
    nom: 'Français',
    // Messages de démarrage
    moteur_manquant: 'ATTENTION : il manque',
    cliquer_engrenage: 'Cliquez ⚙️ (en haut à droite) pour installer.',
    // Boutons
    on_off: 'ON / OFF',
    annuler: 'ANNULER',
    clear: 'CLEAR',
    copier: 'COPIER',
    enregistrement: 'ENREGISTREMENT...',
    copie_ok: 'COPIÉ !',
    audio: 'AUDIO',
    audio_arme: 'Mode AUDIO armé — prochaine dictée sauvée en audio + texte',
    audio_desarme: 'Mode AUDIO désactivé',
    audio_garde: 'Audio + texte sauvegardés dans WAVE',
    erreur_audio: 'Erreur sauvegarde audio',
    // Traduction vers l'anglais (Phase 2)
    traduire: 'TRADUIRE',
    traduire_arme: 'Mode TRADUIRE armé — la dictée sera traduite vers l\'anglais',
    traduire_desarme: 'Mode TRADUIRE désactivé',
    // Webhook n8n (Phase 3)
    envoyer: 'n8n',
    webhook_non_config: 'n8n non configuré — allez dans les réglages ⚙️ pour renseigner l\'URL (et la clé API si nécessaire)',
    webhook_arme: 'Mode n8n armé — chaque dictée sera envoyée vers n8n',
    webhook_desarme: 'Mode n8n désactivé',
    webhook_envoye: 'Envoyé vers n8n ✔',
    webhook_echec: 'Échec envoi webhook',
    webhook_titre: 'Webhook n8n',
    webhook_info: 'Envoyez chaque dictée vers votre n8n (ou tout autre service). Universel.',
    webhook_placeholder: 'http://localhost:5678/webhook/dictee',
    webhook_token_ph: 'Jeton (token) optionnel',
    webhook_sauver: 'Enregistrer',
    webhook_tester: 'Tester',
    webhook_sauve_ok: 'Configuration webhook enregistrée',
    webhook_test_encours: 'Test en cours...',
    webhook_test_ok: 'Webhook OK ✔',
    // Modale
    titre_modale: '⚙️ Mises à jour & Modèles',
    gpu_detecte: 'GPU détecté',
    gpu_redetect: '↻ Redétecter',
    gpu_redetect_ok: 'GPU redétecté',
    executable_whisper: 'Exécutable Whisper',
    whisper_exe_instruc: 'Téléchargez cli.zip sur GitHub, dézippez-le dans le dossier Whisper/',
    redemarrer_apres: 'Après install, redémarrez l\'app (⚙️ → bouton rouge) pour la prise en compte.',
    bouton_redemarrer: '🔄 Redémarrer l\'app',
    installer_auto: '⚡ Installer auto',
    extraction: 'Décompression en cours...',
    redemarrage: 'Redémarrage de l\'app...',
    tableau_modeles: 'Tableau comparatif des modèles :',
    telechargement_gestion: 'Téléchargement / gestion :',
    fermer: 'Fermer',
    actif: 'Actif',
    installe: 'Installé',
    supprimer: 'Supprimer',
    telecharger: 'Télécharger',
    telechargement_cours: 'Téléchargement…',
    en_file: 'En file d\'attente',
    verification: 'Vérification...',
    // Mises à jour (bouton global)
    tout_verifier: 'Tout vérifier',
    maj_global_titre: 'Mises à jour',
    maj_app: 'Application',
    maj_a_jour: 'À jour',
    maj_dispo: 'MAJ dispo',
    derniere_version: 'Dernière version',
    ouvrir: 'Ouvrir',
    maj_telechargement: 'Téléchargement de la mise à jour…',
    maj_installation: 'Installation…',
    maj_redemarrage_auto: 'Mise à jour terminée, redémarrage…',
    maj_maintenant: 'Mettre à jour maintenant',
    maj_echec: 'Échec de la mise à jour : ',
    // Toasts
    sauvegarde_ok: 'Sauvegardé',
    ecran_efface: 'Écran effacé',
    selection_supprimee: 'Sélection supprimée',
    nouvelle_note: 'Nouvelle note',
    pas_fichier_texte: 'n\'est pas un fichier texte',
    erreur_lecture: 'Erreur lecture',
    fichier_insere: 'fichier(s) inséré(s)',
    aucun_son: 'Aucun son capté',
    transcription_en_cours: 'Transcription en cours...',
    transcrip_vide: "[Whisper n'a rien transcrit]",
    erreur_transcrip: '[ERREUR TRANSCRIPTION] :',
    // Nav
    modele: 'Modèle',
    modele_manquant: 'Modèle manquant',
    gpu_incompatible: 'GPU incompatible — Whisper nécessite une carte graphique supportant DirectX 11+. Carte trop ancienne, GPU désactivé, ou machine virtuelle sans GPU.',
    langue: 'Langue',
    tooltip_vram: "⚠️ Attention : la VRAM est la mémoire de votre carte graphique. Pensez aux autres logiciels lourds que vous utilisez en même temps (jeux, génération d'images, intelligence artificielle). Si le total dépasse la capacité de votre carte, le PC peut ramer ou planter.",
    // Correcteur d'orthographe (LanguageTool)
    correcteur_ortho: 'Correcteur',
    chargement: 'Chargement...',
    installer: 'Installer',
    correcteur_non_installe: 'Non installé — cliquez sur Installer (~350 Mo)',
    correcteur_pret: 'Prêt',
    correcteur_installe_off: 'Installé mais serveur arrêté',
    demarrer_serveur: 'Démarrer',
    correcteur_dl_java: 'Téléchargement de Java...',
    correcteur_dl_lt: 'Téléchargement de LanguageTool...',
    correcteur_demarrage: 'Démarrage du serveur...',
    correcteur_echec: 'Échec du correcteur',
    corrections_appliquees: 'correction(s) appliquée(s)',
    mode_correction: 'Mode de correction',
    mode_correction_info: 'Auto = corrige en silence. Semi = ouvre un panneau de relecture.',
    mode_off: 'Désactivé',
    mode_auto: 'Automatique',
    mode_semi: 'Semi-auto (panneau)',
    relecture_titre: 'Relecture',
    relecture_finie: 'Relecture terminée',
    aucune_proposition: 'Aucune proposition automatique (règle de grammaire).',
    propositions: 'Propositions :',
    ignorer: 'Ignorer',
    dico_ajouter: 'Dico',
    terminer: 'Terminer',
    dico_personnel: 'Dictionnaire personnel',
    dico_info: 'Mots à ne plus signaler (noms propres, jargon). Séparez par des virgules.',
    dico_placeholder: 'ex : Ponpon, ZCode, Jarvis',
    dico_vide: 'Aucun mot ajouté pour le moment.',
    dico_ajoute: 'mot ajouté',
    ajouter: 'Ajouter',
    // Avertissement désinstallation
  },

  // ===== ANGLAIS =====
  en: {
    nom: 'English',
    moteur_manquant: 'WARNING:',
    cliquer_engrenage: 'is missing. Click ⚙️ (top right) to install.',
    on_off: 'ON / OFF',
    annuler: 'CANCEL',
    clear: 'CLEAR',
    copier: 'COPY',
    enregistrement: 'RECORDING...',
    copie_ok: 'COPIED!',
    audio: 'AUDIO',
    audio_arme: 'AUDIO mode armed — next dictation saved as audio + text',
    audio_desarme: 'AUDIO mode disabled',
    audio_garde: 'Audio + text saved in WAVE',
    erreur_audio: 'Audio save error',
    traduire: 'TRANSLATE',
    traduire_arme: 'TRANSLATE mode armed — dictation will be translated into English',
    traduire_desarme: 'TRANSLATE mode disabled',
    envoyer: 'n8n',
    webhook_non_config: 'n8n not configured — go to settings ⚙️ to set the URL (and API key if needed)',
    webhook_arme: 'n8n mode armed — each dictation will be sent to n8n',
    webhook_desarme: 'n8n mode disabled',
    webhook_envoye: 'Sent to n8n ✔',
    webhook_echec: 'Webhook send failed',
    webhook_titre: 'n8n Webhook',
    webhook_info: 'Send each dictation to your n8n (or any other service). Universal.',
    webhook_placeholder: 'http://localhost:5678/webhook/dictation',
    webhook_token_ph: 'Optional token',
    webhook_sauver: 'Save',
    webhook_tester: 'Test',
    webhook_sauve_ok: 'Webhook configuration saved',
    webhook_test_encours: 'Testing...',
    webhook_test_ok: 'Webhook OK ✔',
    titre_modale: '⚙️ Updates & Models',
    gpu_detecte: 'Detected GPU',
    gpu_redetect: '↻ Re-detect',
    gpu_redetect_ok: 'GPU re-detected',
    executable_whisper: 'Whisper executable',
    whisper_exe_instruc: 'Download cli.zip on GitHub, unzip it into the Whisper/ folder',
    redemarrer_apres: 'After install, restart the app (⚙️ → red button) to take effect.',
    bouton_redemarrer: '🔄 Restart app',
    installer_auto: '⚡ Auto install',
    extraction: 'Extracting...',
    redemarrage: 'Restarting app...',
    tableau_modeles: 'Model comparison table:',
    telechargement_gestion: 'Download / management:',
    fermer: 'Close',
    actif: 'Active',
    installe: 'Installed',
    supprimer: 'Delete',
    telecharger: 'Download',
    telechargement_cours: 'Downloading…',
    en_file: 'Queued',
    verification: 'Checking...',
    // Mises à jour (bouton global)
    tout_verifier: 'Check all',
    maj_global_titre: 'Updates',
    maj_app: 'Application',
    maj_a_jour: 'Up to date',
    maj_dispo: 'Update available',
    derniere_version: 'Latest version',
    ouvrir: 'Open',
    maj_telechargement: 'Downloading update…',
    maj_installation: 'Installing…',
    maj_redemarrage_auto: 'Update complete, restarting…',
    maj_maintenant: 'Update now',
    maj_echec: 'Update failed: ',
    sauvegarde_ok: 'Saved',
    ecran_efface: 'Screen cleared',
    selection_supprimee: 'Selection deleted',
    nouvelle_note: 'New note',
    pas_fichier_texte: 'is not a text file',
    erreur_lecture: 'Read error',
    fichier_insere: 'file(s) inserted',
    aucun_son: 'No sound captured',
    transcription_en_cours: 'Transcribing...',
    transcrip_vide: '[Whisper transcribed nothing]',
    erreur_transcrip: '[TRANSCRIPTION ERROR]:',
    modele: 'Model',
    modele_manquant: 'Missing model',
    gpu_incompatible: 'Incompatible GPU — Whisper requires a DirectX 11+ graphics card. Card too old, GPU disabled, or virtual machine without GPU.',
    langue: 'Language',
    tooltip_vram: "⚠️ Warning: VRAM is your graphics card memory. Consider other heavy software you use at the same time (games, image generation, AI). If the total exceeds your card's capacity, the PC may slow down or crash.",
    correcteur_ortho: 'Spellchecker',
    chargement: 'Loading...',
    installer: 'Install',
    correcteur_non_installe: 'Not installed — click Install (~350 MB)',
    correcteur_pret: 'Ready',
    correcteur_installe_off: 'Installed but server stopped',
    demarrer_serveur: 'Start',
    correcteur_dl_java: 'Downloading Java...',
    correcteur_dl_lt: 'Downloading LanguageTool...',
    correcteur_demarrage: 'Starting server...',
    correcteur_echec: 'Spellchecker failed',
    corrections_appliquees: 'correction(s) applied',
    mode_correction: 'Correction mode',
    mode_correction_info: 'Auto = silent correction. Semi = opens a review panel.',
    mode_off: 'Disabled',
    mode_auto: 'Automatic',
    mode_semi: 'Semi-auto (panel)',
    relecture_titre: 'Review',
    relecture_finie: 'Review finished',
    aucune_proposition: 'No automatic suggestion (grammar rule).',
    propositions: 'Suggestions:',
    ignorer: 'Ignore',
    dico_ajouter: 'Dict',
    terminer: 'Done',
    dico_personnel: 'Personal dictionary',
    dico_info: 'Words to no longer flag (proper nouns, jargon). Separate with commas.',
    dico_placeholder: 'e.g. John, Acme, Jarvis',
    dico_vide: 'No words added yet.',
    dico_ajoute: 'word added',
    ajouter: 'Add',
  },

  // ===== ESPAGNOL =====
  es: {
    nom: 'Español',
    moteur_manquant: 'ATENCIÓN:',
    cliquer_engrenage: 'falta. Haga clic en ⚙️ (arriba a la derecha) para instalar.',
    on_off: 'ON / OFF',
    annuler: 'CANCELAR',
    clear: 'BORRAR',
    copier: 'COPIAR',
    enregistrement: 'GRABANDO...',
    copie_ok: '¡COPIADO!',
    audio: 'AUDIO',
    audio_arme: 'Modo AUDIO armado — próximo dictado guardado en audio + texto',
    audio_desarme: 'Modo AUDIO desactivado',
    audio_garde: 'Audio + texto guardados en WAVE',
    erreur_audio: 'Error al guardar audio',
    traduire: 'TRADUCIR',
    traduire_arme: 'Modo TRADUCIR armado — el dictado se traducirá al inglés',
    traduire_desarme: 'Modo TRADUCIR desactivado',
    envoyer: 'n8n',
    webhook_non_config: 'n8n no configurado — vaya a ajustes ⚙️ para indicar la URL (y la clave API si es necesario)',
    webhook_arme: 'Modo n8n armado — cada dictado se enviará a n8n',
    webhook_desarme: 'Modo n8n desactivado',
    webhook_envoye: 'Enviado a n8n ✔',
    webhook_echec: 'Error envío webhook',
    webhook_titre: 'Webhook n8n',
    webhook_info: 'Envíe cada dictado a su n8n (o cualquier otro servicio). Universal.',
    webhook_placeholder: 'http://localhost:5678/webhook/dictado',
    webhook_token_ph: 'Token opcional',
    webhook_sauver: 'Guardar',
    webhook_tester: 'Probar',
    webhook_sauve_ok: 'Configuración webhook guardada',
    webhook_test_encours: 'Probando...',
    webhook_test_ok: 'Webhook OK ✔',
    titre_modale: '⚙️ Actualizaciones y Modelos',
    gpu_detecte: 'GPU detectada',
    gpu_redetect: '↻ Redetectar',
    gpu_redetect_ok: 'GPU redetectada',
    executable_whisper: 'Ejecutable Whisper',
    whisper_exe_instruc: 'Descargue cli.zip en GitHub, descomprímalo en la carpeta Whisper/',
    redemarrer_apres: 'Tras instalar, reinicie la app (⚙️ → botón rojo) para que surta efecto.',
    bouton_redemarrer: '🔄 Reiniciar app',
    installer_auto: '⚡ Instalar auto',
    extraction: 'Descomprimiendo...',
    redemarrage: 'Reiniciando app...',
    tableau_modeles: 'Tabla comparativa de modelos:',
    telechargement_gestion: 'Descarga / gestión:',
    fermer: 'Cerrar',
    actif: 'Activo',
    installe: 'Instalado',
    supprimer: 'Eliminar',
    telecharger: 'Descargar',
    telechargement_cours: 'Descargando…',
    en_file: 'En cola',
    verification: 'Comprobando...',
    // Mises à jour (bouton global)
    tout_verifier: 'Comprobar todo',
    maj_global_titre: 'Actualizaciones',
    maj_app: 'Aplicación',
    maj_a_jour: 'Actualizado',
    maj_dispo: 'Actualización disponible',
    derniere_version: 'Última versión',
    ouvrir: 'Abrir',
    maj_telechargement: 'Descargando actualización…',
    maj_installation: 'Instalando…',
    maj_redemarrage_auto: 'Actualización completada, reiniciando…',
    maj_maintenant: 'Actualizar ahora',
    maj_echec: 'Error de actualización: ',
    sauvegarde_ok: 'Guardado',
    ecran_efface: 'Pantalla borrada',
    selection_supprimee: 'Selección eliminada',
    nouvelle_note: 'Nueva nota',
    pas_fichier_texte: 'no es un archivo de texto',
    erreur_lecture: 'Error de lectura',
    fichier_insere: 'archivo(s) insertado(s)',
    aucun_son: 'No se captó sonido',
    transcription_en_cours: 'Transcribiendo...',
    transcrip_vide: '[Whisper no transcribió nada]',
    erreur_transcrip: '[ERROR DE TRANSCRIPCIÓN]:',
    modele: 'Modelo',
    modele_manquant: 'Modelo faltante',
    gpu_incompatible: 'GPU incompatible — Whisper requiere una tarjeta gráfica compatible con DirectX 11+. Tarjeta demasiado antigua, GPU desactivada o máquina virtual sin GPU.',
    langue: 'Idioma',
    tooltip_vram: "⚠️ Atención: la VRAM es la memoria de su tarjeta gráfica. Tenga en cuenta otros programas pesados que use al mismo tiempo (juegos, generación de imágenes, inteligencia artificial). Si el total supera la capacidad de su tarjeta, el PC puede volverse lento o bloquearse.",
    correcteur_ortho: 'Corrector',
    chargement: 'Cargando...',
    installer: 'Instalar',
    correcteur_non_installe: 'No instalado — haga clic en Instalar (~350 MB)',
    correcteur_pret: 'Listo',
    correcteur_installe_off: 'Instalado pero servidor detenido',
    demarrer_serveur: 'Iniciar',
    correcteur_dl_java: 'Descargando Java...',
    correcteur_dl_lt: 'Descargando LanguageTool...',
    correcteur_demarrage: 'Iniciando servidor...',
    correcteur_echec: 'Error del corrector',
    corrections_appliquees: 'corrección/correcciones aplicada(s)',
    mode_correction: 'Modo de corrección',
    mode_correction_info: 'Auto = corrige en silencio. Semi = abre un panel de revisión.',
    mode_off: 'Desactivado',
    mode_auto: 'Automático',
    mode_semi: 'Semi-auto (panel)',
    relecture_titre: 'Revisión',
    relecture_finie: 'Revisión terminada',
    aucune_proposition: 'Sin sugerencia automática (regla gramatical).',
    propositions: 'Sugerencias:',
    ignorer: 'Ignorar',
    dico_ajouter: 'Dicc',
    terminer: 'Terminar',
    dico_personnel: 'Diccionario personal',
    dico_info: 'Palabras que no señalar (nombres propios, jerga). Separe con comas.',
    dico_placeholder: 'ej : Ponpon, ZCode, Jarvis',
    dico_vide: 'Ninguna palabra añadida todavía.',
    dico_ajoute: 'palabra añadida',
    ajouter: 'Añadir',
  },

  // ===== PORTUGAIS =====
  pt: {
    nom: 'Português',
    moteur_manquant: 'ATENÇÃO:',
    cliquer_engrenage: 'falta. Clique em ⚙️ (em cima à direita) para instalar.',
    on_off: 'ON / OFF',
    annuler: 'CANCELAR',
    clear: 'LIMPAR',
    copier: 'COPIAR',
    enregistrement: 'GRAVANDO...',
    copie_ok: 'COPIADO!',
    audio: 'AUDIO',
    audio_arme: 'Modo AUDIO armado — próximo ditado guardado em áudio + texto',
    audio_desarme: 'Modo AUDIO desativado',
    audio_garde: 'Áudio + texto guardados em WAVE',
    erreur_audio: 'Erro ao guardar áudio',
    traduire: 'TRADUZIR',
    traduire_arme: 'Modo TRADUZIR armado — o ditado será traduzido para inglês',
    traduire_desarme: 'Modo TRADUZIR desativado',
    envoyer: 'n8n',
    webhook_non_config: 'n8n não configurado — vá a definições ⚙️ para indicar o URL (e a chave API se necessário)',
    webhook_arme: 'Modo n8n armado — cada ditado será enviado para o n8n',
    webhook_desarme: 'Modo n8n desativado',
    webhook_envoye: 'Enviado para o n8n ✔',
    webhook_echec: 'Falha no envio do webhook',
    webhook_titre: 'Webhook n8n',
    webhook_info: 'Envie cada ditado para o seu n8n (ou qualquer outro serviço). Universal.',
    webhook_placeholder: 'http://localhost:5678/webhook/ditado',
    webhook_token_ph: 'Token opcional',
    webhook_sauver: 'Guardar',
    webhook_tester: 'Testar',
    webhook_sauve_ok: 'Configuração do webhook guardada',
    webhook_test_encours: 'A testar...',
    webhook_test_ok: 'Webhook OK ✔',
    titre_modale: '⚙️ Atualizações e Modelos',
    gpu_detecte: 'GPU detetada',
    gpu_redetect: '↻ Detetar novamente',
    gpu_redetect_ok: 'GPU detetada novamente',
    executable_whisper: 'Executável Whisper',
    whisper_exe_instruc: 'Descarregue cli.zip no GitHub, descomprima-o na pasta Whisper/',
    redemarrer_apres: 'Após instalar, reinicie a app (⚙️ → botão vermelho) para fazer efeito.',
    bouton_redemarrer: '🔄 Reiniciar app',
    installer_auto: '⚡ Instalar auto',
    extraction: 'A descomprimir...',
    redemarrage: 'A reiniciar app...',
    tableau_modeles: 'Tabela comparativa de modelos:',
    telechargement_gestion: 'Descarga / gestão:',
    fermer: 'Fechar',
    actif: 'Ativo',
    installe: 'Instalado',
    supprimer: 'Apagar',
    telecharger: 'Descarregar',
    telechargement_cours: 'Baixando…',
    en_file: 'Na fila',
    verification: 'A verificar...',
    // Mises à jour (bouton global)
    tout_verifier: 'Verificar tudo',
    maj_global_titre: 'Atualizações',
    maj_app: 'Aplicação',
    maj_a_jour: 'Atualizado',
    maj_dispo: 'Atualização disponível',
    derniere_version: 'Última versão',
    ouvrir: 'Abrir',
    maj_telechargement: 'Baixando atualização…',
    maj_installation: 'Instalando…',
    maj_redemarrage_auto: 'Atualização concluída, reiniciando…',
    maj_maintenant: 'Atualizar agora',
    maj_echec: 'Falha na atualização: ',
    sauvegarde_ok: 'Guardado',
    ecran_efface: 'Ecrã limpo',
    selection_supprimee: 'Seleção eliminada',
    nouvelle_note: 'Nova nota',
    pas_fichier_texte: 'não é um ficheiro de texto',
    erreur_lecture: 'Erro de leitura',
    fichier_insere: 'ficheiro(s) inserido(s)',
    aucun_son: 'Nenhum som captado',
    transcription_en_cours: 'A transcrever...',
    transcrip_vide: '[Whisper não transcreveu nada]',
    erreur_transcrip: '[ERRO DE TRANSCRIÇÃO]:',
    modele: 'Modelo',
    modele_manquant: 'Modelo em falta',
    gpu_incompatible: 'GPU incompatível — o Whisper requer uma placa gráfica compatível com DirectX 11+. Placa demasiado antiga, GPU desativada ou máquina virtual sem GPU.',
    langue: 'Idioma',
    tooltip_vram: "⚠️ Atenção: a VRAM é a memória da sua placa gráfica. Considere outros programas pesados que usa ao mesmo tempo (jogos, geração de imagens, inteligência artificial). Se o total ultrapassar a capacidade da sua placa, o PC pode ficar lento ou bloquear.",
    correcteur_ortho: 'Corretor',
    chargement: 'A carregar...',
    installer: 'Instalar',
    correcteur_non_installe: 'Não instalado — clique em Instalar (~350 MB)',
    correcteur_pret: 'Pronto',
    correcteur_installe_off: 'Instalado mas servidor parado',
    demarrer_serveur: 'Iniciar',
    correcteur_dl_java: 'A descarregar Java...',
    correcteur_dl_lt: 'A descarregar LanguageTool...',
    correcteur_demarrage: 'A iniciar servidor...',
    correcteur_echec: 'Falha do corretor',
    corrections_appliquees: 'correção/correções aplicada(s)',
    mode_correction: 'Modo de correção',
    mode_correction_info: 'Auto = corrige em silêncio. Semi = abre um painel de revisão.',
    mode_off: 'Desativado',
    mode_auto: 'Automático',
    mode_semi: 'Semi-auto (painel)',
    relecture_titre: 'Revisão',
    relecture_finie: 'Revisão terminada',
    aucune_proposition: 'Sem sugestão automática (regra gramatical).',
    propositions: 'Sugestões:',
    ignorer: 'Ignorar',
    dico_ajouter: 'Dicio',
    terminer: 'Terminar',
    dico_personnel: 'Dicionário pessoal',
    dico_info: 'Palavras a não assinalar (nomes próprios, jargão). Separe com vírgulas.',
    dico_placeholder: 'ex : Ponpon, ZCode, Jarvis',
    dico_vide: 'Nenhuma palavra adicionada ainda.',
    dico_ajoute: 'palavra adicionada',
    ajouter: 'Adicionar',
  },

  // ===== ALLEMAND =====
  de: {
    nom: 'Deutsch',
    moteur_manquant: 'ACHTUNG:',
    cliquer_engrenage: 'fehlt. Klicken Sie auf ⚙️ (oben rechts) zum Installieren.',
    on_off: 'ON / OFF',
    annuler: 'ABBRECHEN',
    clear: 'LÖSCHEN',
    copier: 'KOPIEREN',
    enregistrement: 'AUFNAHME...',
    copie_ok: 'KOPIERT!',
    audio: 'AUDIO',
    audio_arme: 'AUDIO-Modus scharfgestellt — nächste Diktat wird als Audio + Text gespeichert',
    audio_desarme: 'AUDIO-Modus deaktiviert',
    audio_garde: 'Audio + Text in WAVE gespeichert',
    erreur_audio: 'Fehler beim Speichern des Audios',
    traduire: 'ÜBERSETZEN',
    traduire_arme: 'ÜBERSETZEN-Modus scharfgestellt — Diktat wird ins Englische übersetzt',
    traduire_desarme: 'ÜBERSETZEN-Modus deaktiviert',
    envoyer: 'n8n',
    webhook_non_config: 'n8n nicht konfiguriert — gehen Sie zu Einstellungen ⚙️, um die URL einzugeben (und API-Schlüssel falls nötig)',
    webhook_arme: 'n8n-Modus scharfgestellt — jedes Diktat wird an n8n gesendet',
    webhook_desarme: 'n8n-Modus deaktiviert',
    webhook_envoye: 'An n8n gesendet ✔',
    webhook_echec: 'Webhook-Versand fehlgeschlagen',
    webhook_titre: 'n8n Webhook',
    webhook_info: 'Senden Sie jedes Diktat an Ihr n8n (oder einen anderen Dienst). Universell.',
    webhook_placeholder: 'http://localhost:5678/webhook/diktat',
    webhook_token_ph: 'Optionales Token',
    webhook_sauver: 'Speichern',
    webhook_tester: 'Testen',
    webhook_sauve_ok: 'Webhook-Konfiguration gespeichert',
    webhook_test_encours: 'Teste...',
    webhook_test_ok: 'Webhook OK ✔',
    titre_modale: '⚙️ Updates & Modelle',
    gpu_detecte: 'Erkannte GPU',
    gpu_redetect: '↻ Neu erkennen',
    gpu_redetect_ok: 'GPU neu erkannt',
    executable_whisper: 'Whisper-Ausführdatei',
    whisper_exe_instruc: 'Laden Sie cli.zip auf GitHub herunter, entpacken Sie es in den Ordner Whisper/',
    redemarrer_apres: 'Nach der Installation starten Sie die App neu (⚙️ → roter Button), um wirksam zu werden.',
    bouton_redemarrer: '🔄 App neu starten',
    installer_auto: '⚡ Auto installieren',
    extraction: 'Entpacken...',
    redemarrage: 'App wird neu gestartet...',
    tableau_modeles: 'Modell-Vergleichstabelle:',
    telechargement_gestion: 'Download / Verwaltung:',
    fermer: 'Schließen',
    actif: 'Aktiv',
    installe: 'Installiert',
    supprimer: 'Löschen',
    telecharger: 'Herunterladen',
    telechargement_cours: 'Wird heruntergeladen…',
    en_file: 'In Warteschlange',
    verification: 'Prüfung...',
    // Mises à jour (bouton global)
    tout_verifier: 'Alle prüfen',
    maj_global_titre: 'Updates',
    maj_app: 'Anwendung',
    maj_a_jour: 'Aktuell',
    maj_dispo: 'Update verfügbar',
    derniere_version: 'Neueste Version',
    ouvrir: 'Öffnen',
    maj_telechargement: 'Update wird heruntergeladen…',
    maj_installation: 'Installiere…',
    maj_redemarrage_auto: 'Update abgeschlossen, Neustart…',
    maj_maintenant: 'Jetzt aktualisieren',
    maj_echec: 'Update fehlgeschlagen: ',
    sauvegarde_ok: 'Gespeichert',
    ecran_efface: 'Bildschirm gelöscht',
    selection_supprimee: 'Auswahl gelöscht',
    nouvelle_note: 'Neue Notiz',
    pas_fichier_texte: 'ist keine Textdatei',
    erreur_lecture: 'Lesefehler',
    fichier_insere: 'Datei(en) eingefügt',
    aucun_son: 'Kein Ton erfasst',
    transcription_en_cours: 'Transkribiere...',
    transcrip_vide: '[Whisper hat nichts transkribiert]',
    erreur_transcrip: '[TRANSKRIPTIONSFEHLER]:',
    modele: 'Modell',
    modele_manquant: 'Modell fehlt',
    gpu_incompatible: 'Inkompatible GPU — Whisper erfordert eine DirectX 11+ fähige Grafikkarte. Karte zu alt, GPU deaktiviert oder virtuelle Maschine ohne GPU.',
    langue: 'Sprache',
    tooltip_vram: "⚠️ Achtung: VRAM ist der Speicher Ihrer Grafikkarte. Denken Sie an andere schwere Software, die Sie gleichzeitig verwenden (Spiele, Bildgenerierung, KI). Wenn die Summe die Kapazität Ihrer Karte übersteigt, kann der PC langsam werden oder abstürzen.",
    correcteur_ortho: 'Rechtschreibprüfung',
    chargement: 'Laden...',
    installer: 'Installieren',
    correcteur_non_installe: 'Nicht installiert — auf Installieren klicken (~350 MB)',
    correcteur_pret: 'Bereit',
    correcteur_installe_off: 'Installiert, aber Server gestoppt',
    demarrer_serveur: 'Starten',
    correcteur_dl_java: 'Java wird heruntergeladen...',
    correcteur_dl_lt: 'LanguageTool wird heruntergeladen...',
    correcteur_demarrage: 'Server wird gestartet...',
    correcteur_echec: 'Rechtschreibprüfung fehlgeschlagen',
    corrections_appliquees: 'Korrektur(en) angewendet',
    mode_correction: 'Korrekturmodus',
    mode_correction_info: 'Auto = korrigiert still. Semi = öffnet ein Prüfungsfeld.',
    mode_off: 'Deaktiviert',
    mode_auto: 'Automatisch',
    mode_semi: 'Semi-auto (Feld)',
    relecture_titre: 'Prüfung',
    relecture_finie: 'Prüfung beendet',
    aucune_proposition: 'Kein automatischer Vorschlag (Grammatikregel).',
    propositions: 'Vorschläge:',
    ignorer: 'Ignorieren',
    dico_ajouter: 'Wb.',
    terminer: 'Fertig',
    dico_personnel: 'Persönliches Wörterbuch',
    dico_info: 'Wörter, die nicht markiert werden (Eigennamen, Jargon). Durch Kommas trennen.',
    dico_placeholder: 'z.B. Ponpon, ZCode, Jarvis',
    dico_vide: 'Noch keine Wörter hinzugefügt.',
    dico_ajoute: 'Wort hinzugefügt',
    ajouter: 'Hinzufügen',
  },

  // ===== ITALIEN =====
  it: {
    nom: 'Italiano',
    moteur_manquant: 'ATTENZIONE:',
    cliquer_engrenage: 'manca. Clicca su ⚙️ (in alto a destra) per installare.',
    on_off: 'ON / OFF',
    annuler: 'ANNULLA',
    clear: 'CANCELLA',
    copier: 'COPIA',
    enregistrement: 'REGISTRAZIONE...',
    copie_ok: 'COPIATO!',
    audio: 'AUDIO',
    audio_arme: 'Modalità AUDIO armata — prossima dettatura salvata in audio + testo',
    audio_desarme: 'Modalità AUDIO disattivata',
    audio_garde: 'Audio + testo salvati in WAVE',
    erreur_audio: 'Errore salvataggio audio',
    traduire: 'TRADUCI',
    traduire_arme: 'Modalità TRADUCI armata — la dettatura sarà tradotta in inglese',
    traduire_desarme: 'Modalità TRADUCI disattivata',
    envoyer: 'n8n',
    webhook_non_config: 'n8n non configurato — vai a impostazioni ⚙️ per inserire l\'URL (e la chiave API se necessario)',
    webhook_arme: 'Modalità n8n armata — ogni dettatura sarà inviata a n8n',
    webhook_desarme: 'Modalità n8n disattivata',
    webhook_envoye: 'Inviato a n8n ✔',
    webhook_echec: 'Invio webhook fallito',
    webhook_titre: 'Webhook n8n',
    webhook_info: 'Invia ogni dettatura al tuo n8n (o qualsiasi altro servizio). Universale.',
    webhook_placeholder: 'http://localhost:5678/webhook/dettatura',
    webhook_token_ph: 'Token opzionale',
    webhook_sauver: 'Salva',
    webhook_tester: 'Prova',
    webhook_sauve_ok: 'Configurazione webhook salvata',
    webhook_test_encours: 'Prova in corso...',
    webhook_test_ok: 'Webhook OK ✔',
    titre_modale: '⚙️ Aggiornamenti e Modelli',
    gpu_detecte: 'GPU rilevata',
    gpu_redetect: '↻ Rileva di nuovo',
    gpu_redetect_ok: 'GPU rilevata di nuovo',
    executable_whisper: 'Eseguibile Whisper',
    whisper_exe_instruc: 'Scarica cli.zip su GitHub, decomprimilo nella cartella Whisper/',
    redemarrer_apres: 'Dopo l\'installazione, riavvia l\'app (⚙️ → pulsante rosso) per renderla effettiva.',
    bouton_redemarrer: '🔄 Riavvia app',
    installer_auto: '⚡ Installa auto',
    extraction: 'Decompressione...',
    redemarrage: 'Riavvio app...',
    tableau_modeles: 'Tabella comparativa dei modelli:',
    telechargement_gestion: 'Download / gestione:',
    fermer: 'Chiudi',
    actif: 'Attivo',
    installe: 'Installato',
    supprimer: 'Elimina',
    telecharger: 'Scarica',
    telechargement_cours: 'Download in corso…',
    en_file: 'In coda',
    verification: 'Verifica...',
    // Mises à jour (bouton global)
    tout_verifier: 'Verifica tutto',
    maj_global_titre: 'Aggiornamenti',
    maj_app: 'Applicazione',
    maj_a_jour: 'Aggiornato',
    maj_dispo: 'Aggiornamento disponibile',
    derniere_version: 'Ultima versione',
    ouvrir: 'Apri',
    maj_telechargement: 'Download aggiornamento…',
    maj_installation: 'Installazione…',
    maj_redemarrage_auto: 'Aggiornamento completato, riavvio…',
    maj_maintenant: 'Aggiorna ora',
    maj_echec: 'Aggiornamento fallito: ',
    sauvegarde_ok: 'Salvato',
    ecran_efface: 'Schermo cancellato',
    selection_supprimee: 'Selezione eliminata',
    nouvelle_note: 'Nuova nota',
    pas_fichier_texte: 'non è un file di testo',
    erreur_lecture: 'Errore di lettura',
    fichier_insere: 'file inserito/i',
    aucun_son: 'Nessun suono captato',
    transcription_en_cours: 'Trascrizione in corso...',
    transcrip_vide: '[Whisper non ha trascritto nulla]',
    erreur_transcrip: '[ERRORE DI TRASCRIZIONE]:',
    modele: 'Modello',
    modele_manquant: 'Modello mancante',
    gpu_incompatible: 'GPU incompatibile — Whisper richiede una scheda grafica compatibile con DirectX 11+. Scheda troppo vecchia, GPU disattivata o macchina virtuale senza GPU.',
    langue: 'Lingua',
    tooltip_vram: "⚠️ Attenzione: la VRAM è la memoria della tua scheda grafica. Considera altri programmi pesanti che usi allo stesso tempo (giochi, generazione di immagini, intelligenza artificiale). Se il totale supera la capacità della tua scheda, il PC può rallentare o bloccarsi.",
    correcteur_ortho: 'Correttore',
    chargement: 'Caricamento...',
    installer: 'Installa',
    correcteur_non_installe: 'Non installato — clicca su Installa (~350 MB)',
    correcteur_pret: 'Pronto',
    correcteur_installe_off: 'Installato ma server fermato',
    demarrer_serveur: 'Avvia',
    correcteur_dl_java: 'Download di Java...',
    correcteur_dl_lt: 'Download di LanguageTool...',
    correcteur_demarrage: 'Avvio del server...',
    correcteur_echec: 'Correttore non riuscito',
    corrections_appliquees: 'correzione/correzioni applicata/e',
    mode_correction: 'Modalità correzione',
    mode_correction_info: 'Auto = corregge in silenzio. Semi = apre un pannello di revisione.',
    mode_off: 'Disattivato',
    mode_auto: 'Automatico',
    mode_semi: 'Semi-auto (pannello)',
    relecture_titre: 'Revisione',
    relecture_finie: 'Revisione terminata',
    aucune_proposition: 'Nessun suggerimento automatico (regola grammaticale).',
    propositions: 'Suggerimenti:',
    ignorer: 'Ignora',
    dico_ajouter: 'Dizio',
    terminer: 'Termina',
    dico_personnel: 'Dizionario personale',
    dico_info: 'Parole da non segnalare (nomi propri, gergo). Separare con virgole.',
    dico_placeholder: 'es : Ponpon, ZCode, Jarvis',
    dico_vide: 'Nessuna parola aggiunta ancora.',
    dico_ajoute: 'parola aggiunta',
    ajouter: 'Aggiungi',
  }
};

// Langue par défaut (utilisé si langue.txt absent ou invalide)
const LANGUE_DEFAUT = 'fr';

module.exports = { TEXTES, LANGUE_DEFAUT };
